build.gradle, src/main/java/com/back/moment/boards/controller/BoardController.java, src/main/java/com/back/moment/boards/dto/BoardListResponseDto.java, src/main/java/com/back/moment/boards/entity/Board.java, src/main/java/com/back/moment/boards/repository/BoardRepository.java, src/main/java/com/back/moment/boards/service/BoardService.java, src/main/java/com/back/moment/common/TimeStamped.java, src/main/java/com/back/moment/exception/ApiException.java, src/main/java/com/back/moment/exception/ErrorResponse.java, src/main/java/com/back/moment/exception/ExceptionEnum.java, src/main/java/com/back/moment/exception/GlobalExceptionHandler.java, src/main/java/com/back/moment/feed/controller/FeedController.java, src/main/java/com/back/moment/users/config/WebSecurityConfig.java, src/main/java/com/back/moment/users/controller/UserController.java, src/main/java/com/back/moment/users/jwt/JwtAuthFilter.java, src/main/java/com/back/moment/users/service/UserService.java, src/main/resources/application.yml
Body : 게시물 전체 조회 시 query문 속 인자값 인식 오류로 인해 dto 생성자를 객체 자체로 받도록 수정하고 게시물 관련 태그 내용을 id가 아닌 string 값들을 출력하도록 board entity 상에 로직을 추가함
=> Fix : 게시물 생성 시 사진 추가 기능 추가 

src/main/java/com/back/moment/boards/controller/BoardController.java, src/main/java/com/back/moment/boards/dto/BoardDetailResponseDto.java, src/main/java/com/back/moment/boards/entity/Board.java, src/main/java/com/back/moment/boards/service/BoardService.java, src/main/java/com/back/moment/exception/ExceptionEnum.java, src/main/java/com/back/moment/feed/controller/FeedController.java, src/main/java/com/back/moment/feed/dto/FeedDetailResponseDto.java, src/main/java/com/back/moment/feed/dto/FeedListResponseDto.java, src/main/java/com/back/moment/feed/service/FeedService.java, src/main/java/com/back/moment/love/repository/LoveRepository.java, src/main/java/com/back/moment/photos/dto/PhotoFeedResponseDto.java, src/main/java/com/back/moment/photos/dto/PhotoMyPageResponseDto.java, src/main/java/com/back/moment/photos/entity/Photo.java, src/main/java/com/back/moment/photos/repository/PhotoRepository.java, src/main/java/com/back/moment/recommend/entity/Recommend.java, src/main/java/com/back/moment/recommend/repository/RecommendRepository.java, src/main/java/com/back/moment/s3/S3Uploader.java, src/main/java/com/back/moment/users/controller/MyPageController.java, src/main/java/com/back/moment/users/dto/MyPageResponseDto.java, src/main/java/com/back/moment/users/entity/Users.java, src/main/java/com/back/moment/users/jwt/JwtAuthFilter.java, src/main/java/com/back/moment/users/repository/UsersRepository.java, src/main/java/com/back/moment/users/security/UserDetailsServiceImpl.java, src/main/java/com/back/moment/users/service/MyPageService.java, src/main/java/com/back/moment/users/service/UserService.java
Body : 회원에 대한 추천과 사진에 대한 좋아요 기능 추가, 피드 상세 조회 및 조회 추가, 게시판 상세 조회 및 조회 & 삭제 기능 추가, 마이 페이지 조회 & 사진 삭제 기능 추가
=> Feat : 전체적 로직 구현

src/main/java/com/back/moment/boards/service/BoardService.java, src/main/java/com/back/moment/exception/ExceptionEnum.java, src/main/java/com/back/moment/oauth/KakaoService.java, src/main/java/com/back/moment/users/dto/SignupRequestDto.java, src/main/java/com/back/moment/users/entity/GenderEnum.java, src/main/java/com/back/moment/users/entity/Users.java, src/main/java/com/back/moment/users/jwt/JwtAuthFilter.java, src/main/java/com/back/moment/users/jwt/JwtUtil.java, src/main/java/com/back/moment/users/service/MyPageService.java, src/main/java/com/back/moment/users/service/UserService.java
Body : 카카오 로그인 시 role 지정 부재로 인해 토큰에 role정보 제거와 마이 페이지 수정에서 role이 null일 경우에만 role을 수정 가능 하도록 하는 변경과 role이 null일 경우 게시물 작성이 불가하도록 조치
=> Fix : 성별 변수 이름 변경 / 카카오 로그인 시 role 지정 부재 문제 해결

build.gradle, src/main/java/com/back/moment/boards/service/BoardService.java, src/main/java/com/back/moment/email/controller/EmailController.java, src/main/java/com/back/moment/photos/dto/PhotoFeedResponseDto.java, src/main/java/com/back/moment/s3/Handler2.java, src/main/java/com/back/moment/s3/S3Config.java, src/main/java/com/back/moment/users/config/WebSecurityConfig.java, src/main/java/com/back/moment/users/controller/UserController.java, src/main/java/com/back/moment/users/dto/ForMainResponseDto.java, src/main/java/com/back/moment/users/service/UserService.java, src/main/resources/application.yml
Fix : CORS 에러 수정
Body : CORS 에러 중 응답에 'Access-Control-Allow-Origin' 헤더가 없다는 것을 나타내고 있어서 이부분을 해결하기 위해 @CrossOrigin(origins = "http://localhost:3000")이 코드를 추가해봄
=> Feat : s3 에 lambda 적용(lambda 기능 아직 불가)/RDS 적용

.gitignore, src/main/java/com/back/moment/MomentApplication.java
=> feat(spring) : cors 추가

src/main/java/com/back/moment/MomentApplication.java
momentApplication 에 있던 cors 주석 처리 하였습니다.
=> feat(spring) : cors 변경

src/main/java/com/back/moment/mainPage/controller/MainController.java, src/main/java/com/back/moment/mainPage/service/MainService.java, src/main/java/com/back/moment/users/config/WebSecurityConfig.java
Body : 초기 페이지 사진 9장 + home 화면 모두 접근 가능하도록 조치 + home 화면에 role에 따른 출력 수정
=> Fix : 프론트 주문에 맞춰 수정

src/main/java/com/back/moment/feed/controller/FeedController.java, src/main/java/com/back/moment/feed/service/FeedService.java, src/test/java/com/back/moment/feed/service/FeedServiceTest.java
Body : 권한 설정으로 인해 api가 겹쳐서 업로드 api 수정
=> Fix : feed 작성 api feeds/upload 로 수정

build.gradle, src/main/java/com/back/moment/feed/dto/FeedDetailResponseDto.java, src/main/java/com/back/moment/feed/service/FeedService.java, src/main/java/com/back/moment/global/config/RedisConfig.java, src/main/java/com/back/moment/global/service/RedisService.java, src/main/java/com/back/moment/oauth/KakaoService.java, src/main/java/com/back/moment/users/entity/RefreshToken.java, src/main/java/com/back/moment/users/service/UserService.java
=> Feat : redis 적용 진행 중

src/main/java/com/back/moment/boards/controller/BoardController.java, src/main/java/com/back/moment/boards/service/BoardService.java
Body : 한 페이지 안의 게시물 개수가 안맞으면은 출력이 안되는 현상 해결
=> Fix : 게시물 전체 조회 수정

src/main/java/com/back/moment/global/config/RedisConfig.java, src/main/java/com/back/moment/global/service/RedisService.java, src/main/java/com/back/moment/oauth/KakaoService.java, src/main/java/com/back/moment/users/jwt/JwtAuthFilter.java, src/main/java/com/back/moment/users/jwt/JwtUtil.java, src/main/java/com/back/moment/users/service/UserService.java
Body : 로그아웃을 통해 redis 속 refreshKey 삭제 구현 요망
=> Feat : 레디스 적용 완료

src/main/java/com/back/moment/email/entity/Email.java, src/main/java/com/back/moment/email/repository/EmailRepository.java, src/main/java/com/back/moment/email/service/EmailService.java, src/main/java/com/back/moment/global/service/RedisService.java, src/main/java/com/back/moment/oauth/KakaoService.java, src/main/java/com/back/moment/users/controller/UserController.java, src/main/java/com/back/moment/users/jwt/JwtAuthFilter.java, src/main/java/com/back/moment/users/jwt/JwtUtil.java, src/main/java/com/back/moment/users/service/UserService.java
Fix : 레디스 맵 형태 key <-> value 교체
=> Feat : email 인증 코드 redis 적용

build.gradle
=> feat(spring) : swagger 적용

src/main/java/com/back/moment/users/controller/UserController.java, src/main/java/com/back/moment/users/entity/Users.java, src/main/java/com/back/moment/users/service/UserService.java
회원탈퇴 soft (탈퇴) / 회원탈퇴 hard (영구삭제)
회원탈퇴는 주석처리 하였습니다.
확인 부탁드립니다 :)
=> feat(spring) : 회원 탈퇴(Hard) 기능 추가 : soft 는 주석처리

src/main/java/com/back/moment/boards/dto/MyPageBoardListResponseDto.java, src/main/java/com/back/moment/boards/entity/Board.java, src/main/java/com/back/moment/boards/repository/BoardRepository.java, src/main/java/com/back/moment/photos/repository/PhotoRepository.java, src/main/java/com/back/moment/users/service/MyPageService.java
Body : 마이 페이지 조회 시 게시물 조회하는 과정에서 N+1 문제로 인해 불필요한 탐색이 들어가는 성능 하락의 원인을 찾았다. 이를 개선하기 위해 fetch join을 활용하여 개선하였다.
=> Fix : 마이페이지 조회 성능 개선

src/main/java/com/back/moment/boards/controller/BoardController.java
=> action test

src/main/java/com/back/moment/users/controller/UserController.java
=> fix(spring) : 회원 탈퇴

src/main/java/com/back/moment/users/config/WebSecurityConfig.java
로그인 하지 않고 board 전체 조회 하도록 권한 수정
=> fix(spring) : WebSecurityConfig 권한 조정 (로그인하지 않고도 board 전체 조회 가능)

src/main/java/com/back/moment/mainPage/service/MainService.java
/home 로그인 하지 않아도 조회 가능하게 고쳤습니다 :)
=> fix(spring) : /home 로그인 하지 않아도 조회 가능

src/main/java/com/back/moment/boards/dto/BoardDetailResponseDto.java, src/main/java/com/back/moment/boards/service/BoardService.java
feedimg + profile 이미지 수정 
확인해주세요 :)
=> fix(spring) : board 상세 조회 수정

src/main/java/com/back/moment/users/dto/MyPageResponseDto.java, src/main/java/com/back/moment/users/service/MyPageService.java
=> fix(spring) : 마이페이지 조회 시 kakaoId 존재여부 확인

src/main/java/com/back/moment/users/service/MyPageService.java
마이페이지 조회 시 게시물의 주인인 host가 나오도록 수정
=> fix(spring) : 마이페이지 조회 시 hostId 로 나오게 수정

src/main/java/com/back/moment/users/service/UserService.java
=> fix(spring) : 회원 가입 시 중복 nickName 인 경우 예외 처리

src/main/java/com/back/moment/boards/controller/BoardController.java, src/main/java/com/back/moment/boards/service/BoardService.java, src/main/java/com/back/moment/exception/GlobalExceptionHandler.java
=> fix(spring) : 예외처리 추가

src/main/java/com/back/moment/exception/GlobalExceptionHandler.java, src/main/java/com/back/moment/global/service/RedisService.java, src/main/java/com/back/moment/users/jwt/JwtUtil.java
=> fix(spring) : refresh, access Token 시간 변경

src/main/java/com/back/moment/feed/service/FeedService.java, src/main/java/com/back/moment/photos/repository/PhotoRepository.java
=> test(spring) : love count 순에서 작성 시간 순으로 변경

src/main/java/com/back/moment/email/service/EmailService.java, src/main/java/com/back/moment/exception/ExceptionEnum.java, src/main/java/com/back/moment/users/controller/UserController.java, src/main/java/com/back/moment/users/entity/Users.java, src/main/java/com/back/moment/users/repository/UsersRepository.java
=> feat(spring) : 비밀번호 변경 이메일 전송

src/main/java/com/back/moment/exception/GlobalExceptionHandler.java
=> test(spring) : 예외처리

src/main/java/com/back/moment/exception/ErrorResponse.java
=> fix(spring) : 예외처리 custom code 번호 전달

src/test/java/com/back/moment/users/service/UserServiceTest.java
이메일 신규 회원 가입, 중복된 닉네임으로 회원 가입, 중복된 이메일로 회원 가입, 프로필 사진 없이 회원 가입(여)
=> test(spring) : 회원가입 테스트 코드

src/test/java/com/back/moment/users/service/UserServiceTest.java
=> test(spring) : 로그인 테스트 코드 작성

src/main/java/com/back/moment/users/service/UserService.java
=> fix(spring) : 로그인 로직 수정

src/main/java/com/back/moment/oauth/KakaoService.java
=> fix(spring) : 카카오 로그인 로직 수정

src/test/java/com/back/moment/users/service/UserServiceTest.java
=> test(spring) : 로그인 성공
